package com.cozy.candybloom

data class Level(val number: Int, val targetScore: Int)

/** 2000 levels, generated by a difficulty curve rather than hand-listed. */
object Levels {
    const val COUNT = 2000

    private fun computeTargetScore(n: Int): Int {
        val base = 800
        val linear = (n - 1) * 220
        val bonus = ((n - 1) / 10) * 150
        return base + linear + bonus
    }

    val all: List<Level> by lazy {
        (1..COUNT).map { n -> Level(n, computeTargetScore(n)) }
    }

    fun byNumber(number: Int): Level = all.getOrNull(number - 1) ?: all.first()
}
